#!/bin/bash

# refreshes the WCA export
# provide a link to the most recent *.tsv database export found here:
# https://www.worldcubeassociation.org/results/misc/export.html

wget -O wca.zip $1

# remove contents of old folder
rm WCA_export/*

mv wca.zip WCA_export/wca.zip
cd WCA_export

unzip wca.zip

rm wca.zip
